// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function MainScreen(props) {
  return React.createElement("div", {
              className: "flex"
            }, React.createElement("p", undefined, "This is the main content of the page."));
}

var make = MainScreen;

export {
  make ,
}
/* react Not a pure module */
