// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function SidebarElement(props) {
  return React.createElement("div", undefined, React.createElement("a", {
                  href: "#"
                }, props.text));
}

var make = SidebarElement;

export {
  make ,
}
/* react Not a pure module */
