// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SidebarUtils from "../ComponentUtils/SidebarUtils.bs.js";

function Sidebar(props) {
  var displayTexts = [
    "Home",
    "About",
    "Services",
    "Contact"
  ];
  return React.createElement("div", {
              className: "bg-primary flex flex-col w-fill h-full min-h-screen p-2"
            }, SidebarUtils.makeElementsForSidebar(displayTexts));
}

var make = Sidebar;

export {
  make ,
}
/* react Not a pure module */
