// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as SidebarElement from "../UI/SidebarElement.bs.js";
import * as JsxPPXReactSupport from "rescript/lib/es6/jsxPPXReactSupport.js";

function makeElementsForSidebar(displayTexts) {
  return Belt_Array.map(displayTexts, (function (text) {
                return JsxPPXReactSupport.createElementWithKey(text, SidebarElement.make, {
                            text: text
                          });
              }));
}

export {
  makeElementsForSidebar ,
}
/* SidebarElement Not a pure module */
