// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Sidebar from "../UI/Sidebar.bs.js";
import * as MainScreen from "../UI/MainScreen.bs.js";

function App(props) {
  return React.createElement("div", {
              className: "bg-primary flex flex-row h-full min-h-screen"
            }, React.createElement(Sidebar.make, {}), React.createElement(MainScreen.make, {}));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
