// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as Client from "react-dom/client";

var rootElement = document.querySelector("#app");

if (rootElement == null) {
  console.log("Whoops");
} else {
  var root = Client.createRoot(rootElement);
  root.render(React.createElement(App.make, {}));
}

export {
  
}
/* rootElement Not a pure module */
